### ISSUE TITLE
Deploy command wants access to my photos

### ISSUE THREAD

**Issue by cotyhamilton** [denoland/deployctl#111] opened 2022-05-09 03:03 UTC
I executed from my home directory, my terminal asked for permission to my photos and I denied then this exception was thrown. I assume it's just trying to walk my whole system from the current working directory. The command takes awhile before it even gets to this.

```sh
cotyhamilton ~
➜ deployctl deploy --project=clever-dog-43 dev/deno-example/wordle/api/mod.ts
✔ Project: clever-dog-43
⠧ Finding static assets...
error: Uncaught (in promise) PermissionDenied: Operation not permitted (os error 1), readdir '/Users/cotyhamilton/Pictures/Photos Library.photoslibrary'
  for await (const file of Deno.readDir(dir)) {
                   ^
    at async Object.[Symbol.asyncIterator] (deno:runtime/js/30_fs.js:125:16)
    at async walk (https://deno.land/x/deploy@1.1.0/src/utils/walk.ts:41:20)
    at async walk (https://deno.land/x/deploy@1.1.0/src/utils/walk.ts:67:18)
    at async walk (https://deno.land/x/deploy@1.1.0/src/utils/walk.ts:67:18)
    at async deploy (https://deno.land/x/deploy@1.1.0/src/subcommands/deploy.ts:153:21)
    at async default (https://deno.land/x/deploy@1.1.0/src/subcommands/deploy.ts:101:3)
    at async https://deno.land/x/deploy@1.1.0/deployctl.ts:101:5
```

It's unfortunate because the install command in the README grants the tool a lot of access.

**Comment by kt3k** [comment] 2022-05-10 09:43
> I executed from my home directory

Executing `deployctl` from home directory is not a good idea as it tries to upload every file from current directory.

> error: Uncaught (in promise) PermissionDenied: Operation not permitted (os error 1), readdir

This was probably caused by the OS's file permissoin, not by Deno's permission, as deployctl already has `--allow-read` permission.

**Comment by satyarohith** [comment] 2022-07-21 09:09
We're now logging the directory that will be uploaded. We are also adding a `--dry-run` flag  (#113) to the deploy command.

Thanks for opening the issue. Closing this as addressed.

**Closed by satyarohith** 2022-07-21 09:09 UTC
